// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnv2u2td6VCU4LC1edPlmAOUma7g-nfQA',
    appId: '1:281915126360:web:ce3c531b7dc2850707d02d',
    messagingSenderId: '281915126360',
    projectId: 'fir-44b69',
    authDomain: 'fir-44b69.firebaseapp.com',
    databaseURL: 'https://fir-44b69-default-rtdb.firebaseio.com',
    storageBucket: 'fir-44b69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZxvPmckap-GvCqSPlckebS4mWILtgN0',
    appId: '1:281915126360:android:3fb334003079485707d02d',
    messagingSenderId: '281915126360',
    projectId: 'fir-44b69',
    databaseURL: 'https://fir-44b69-default-rtdb.firebaseio.com',
    storageBucket: 'fir-44b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQN3gp5JMxEvsNL1iVba2-_COMjTtzRVg',
    appId: '1:281915126360:ios:ddb40ef4c757fa4707d02d',
    messagingSenderId: '281915126360',
    projectId: 'fir-44b69',
    databaseURL: 'https://fir-44b69-default-rtdb.firebaseio.com',
    storageBucket: 'fir-44b69.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQN3gp5JMxEvsNL1iVba2-_COMjTtzRVg',
    appId: '1:281915126360:ios:dfa92e325b2a6a5d07d02d',
    messagingSenderId: '281915126360',
    projectId: 'fir-44b69',
    databaseURL: 'https://fir-44b69-default-rtdb.firebaseio.com',
    storageBucket: 'fir-44b69.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
